.gitignore
---
practicing merge, updating gitignore
=> updated gitignore to ignore webstorm config

.travis.yml, package.json
---
Added customization to add mugshop to travis and package.json from boilermaker defaults
=> added customization to .travis and packagejson from boilermaker

package-lock.json
---
Seeing if package lock json file is saved
=> updated package lock json

server/db/models/Review.js, server/db/models/user.js
---
Added user and review database models
=> user and review database models added

server/db/models/mug.js, server/db/models/tag.js
=> mugs & tags db models

server/db/models/Review.js, server/db/models/index.js, server/index.js
---
Added model associations and some minor edits to Model definitions
=> Model associations and minor edit to model definitions

client/components/all-mugs-card.js, client/components/all-mugs.js, client/components/navbar.js, client/routes.js, package-lock.json, package.json, public/index.html
---
Adding in initial Bootstrap All Product view
=> React bootstrap all products

server/api/cart.js, server/api/index.js, server/api/mugs.js, server/api/reviews.js
---
Added api routes for cart, mugs, reviews, and users - need to check cart routes for accuracy and potentially add more routes later
=> added express api routes

client/components/cart.js, client/routes.js
---
cart component rendering with image and basic info. need to add buttons and figure out sessions for when a guest logs in so that cart items don't disappera
=> cart component rendering with image and basic info

client/components/cart.js
=> cart component being developed

client/components/navbar.js
=> navbar style struggles

client/components/all-mugs.js, script/seed.js, server/api/mugs.js, server/index.js
---
Added all mugs component did mount and rendering mugs from DB
=> All mugs render

client/components/cart.js
=> react cart component floundering

client/components/all-mugs-card.js, client/components/all-mugs.js, server/api/mugs.js, server/index.js
---
Add to Cart button simply logs Mug ID
=> added a handleAdd to Cart but only console logs mug id

client/components/all-mugs-card.js, client/components/all-mugs.js, client/components/cart.js, script/seed.js, server/api/cart.js
=> Cart add item

client/components/cart-card.js, client/components/cart.js, server/api/cart.js
---
Got delete route and button working
=> delete button and route all working

server/api/cart.js, server/api/mugs.js, server/db/models/index.js
=> eager loading mugs from cartItem

client/components/all-mugs.js, client/store/index.js, client/store/mugs.js
=> Mugs reducer created

client/components/cart.js, client/store/cart.js, client/store/index.js
---
cart in redux store set up at most basic level
=> cart in redux store set up at most basic level

client/store/mugs.js, server/api/mugs.js
---
have pagination working and limiting mugs to 20 per page
=> have pagination working and limiting mugs to 20 per page

client/components/single-mug.js, client/routes.js, public/style.css
=> beginnings of singlemug

client/components/all-mugs-card.js, client/components/all-mugs.js, client/routes.js, client/store/index.js, client/store/mugs.js, client/store/tags.js, script/seed.js, server/api/index.js, server/api/tags.js, server/db/models/tag.js
=> Tag reducer

client/index.js, server/api/cart.js, server/api/users.js, server/index.js
=> adds some route protection examples

client/components/all-mugs-card.js, client/components/all-mugs.js
=> started adding buttons for pagination

.travis.yml
=> travis heroku deployment

script/seed.js
=> added two static seeds, user & admin

server/db/models/index.js
=> updated review to capital letter

.travis.yml
=> added test DB for travis

client/components/user-home.spec.js, server/api/users.spec.js, server/db/models/user.spec.js
=> commented out test specs

script/seed.spec.js
---
one more spec file commented out
=> forgot to comment out spec file

client/components/all-mugs.js, client/components/navbar.js, client/routes.js
---
react bootstrap pagination started
=> react bootstrap pagination started

client/components/cart-card.js, client/routes.js, public/style.css, server/api/cart.js
=> cart quantity

client/components/all-mugs-card.js, client/components/cart-card.js, client/store/cart.js, server/api/cart.js
---
Updated the cart to refresh automatically via updating cart redux file. The cart will auto rerender when item is deleted as well as update quantity.
=> delete rerenders automatically as well as update to quantity

client/components/all-mugs.js, public/style.css
---
Next and Prev buttons added
=> pagination simplified and working

client/components/all-mugs-card.js, client/components/cart-card.js, client/components/cart.js, client/components/navbar.js, client/routes.js, package-lock.json, package.json, public/style.css
=> Cart total

client/components/all-orders.js, client/components/cart.js, client/routes.js, client/store/cart.js, client/store/index.js, client/store/orders.js, server/api/cart.js, server/api/index.js, server/api/orders.js, server/db/models/index.js
=> order reducer and all-orders component

client/components/navbar.js, client/components/single-order.js, client/routes.js, server/api/orders.js
=> added single order component

client/components/all-mugs.js, client/components/all-orders.js, client/components/single-order.js
=> all orders and single order component view up

server/api/cart.js, server/api/users.js, server/db/models/cartItem.js, server/db/models/index.js, server/index.js
---
changed DB join table schema, added guest cart persistance (conditionals in cart routes)
=> guestCart & userCart working

client/components/single-order.js, server/auth/index.js
=> have guest cart merge into user cart working

script/seed.js, server/api/cart.js
=> shopping cart quantity limit almost working

client/components/cart-card.js, client/store/cart.js, public/style.css, server/index.js
---
React component, redux thunk, and backend route checks if cart quantity > mug stock
=> various quantity checks on frontend and backend

client/components/admin-page.js, client/components/auth-form.js, client/components/navbar.js, client/routes.js, public/style.css, server/api/cart.js, server/api/users.js
---
Added Admin page and only visible to admin
=> Admin user2

client/components/cart-card.js, server/auth/index.js
---
Fixed bug where cartItem would duplicate on login if guest and user both had the same mug in their cart. Correct behavior is that mugs merge gets skipped.
=> Bug fix many mug

client/components/admin-orders.js, client/components/admin-page.js, client/components/all-orders.js, client/components/cart-card.js, client/components/navbar.js, client/routes.js, client/store/admin.js, client/store/index.js
=> Admin All Orders page renders via admin page

server/api/cart.js
=> stock updates on checkout

client/components/all-orders-card.js, client/components/all-orders.js, client/store/admin.js, server/api/orders.js
---
Order update form for admin working
=> Order update form for admin functioning

client/components/admin-page.js, client/components/admin-users-card.js, client/components/admin-users.js, client/routes.js, client/store/admin.js, public/style.css, server/api/users.js
---
Admin All Users and Admin Orders update options complete
=> Admin user5

client/components/CheckoutForm.js, client/components/MyStoreCheckout.js, client/components/cart.js, client/index.js, client/routes.js, public/index.html
---
checkout with stripe is up and runnin'
=> Stripe component added and working with checkout

client/components/admin-mug-form.js, client/components/admin-mugs-card.js, client/components/admin-mugs.js, client/components/admin-page.js, client/components/navbar.js, client/routes.js, client/store/admin.js, client/store/mugs.js, public/style.css, server/api/mugs.js, server/db/models/mug.js
=> Admin products

client/components/admin-mug-form.js, client/components/admin-mugs-card.js, client/components/admin-mugs.js, client/components/admin-users-card.js, client/components/all-mugs-card.js, client/components/all-mugs.js, client/components/filter.js, client/routes.js, client/store/filter.js, server/api/cart.js, server/api/mugs.js, server/api/reviews.js
=> Admin mug update

client/app.js, client/components/all-mugs.js, client/components/all-orders-card.js, client/components/all-orders.js, client/routes.js, public/style.css
=> Minor cosmetics

server/api/cart.js, server/api/orders.js, server/db/models/index.js, server/db/models/order.js
=> guestcart checkout
